# Generated by Django 3.0.5 on 2020-04-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_image',
            field=models.ImageField(default='profile.JPG', upload_to='profilepics'),
        ),
    ]
