# Generated by Django 3.0.5 on 2020-04-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200427_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='amboitub.PNG', upload_to='postimages'),
        ),
    ]
