# Generated by Django 3.0.5 on 2020-04-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
