# Generated by Django 3.0.5 on 2020-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200428_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('T', 'Technology'), ('E', 'Economics')], max_length=1),
        ),
    ]
